--[[
    -- qb-Lenzh_chopshop
    ["battery"] 		 	 	 	 = {["name"] = "battery",           			["label"] = "Battery",	 			["weight"] = 2000, 		["type"] = "item", 		["image"] = "battery.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle battery"},
    ["muffler"] 		 	 	 	 = {["name"] = "muffler",           			["label"] = "Muffler",	 			["weight"] = 1000, 		["type"] = "item", 		["image"] = "muffler.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle muffler"},
    ["hood"] 		 	 	    	 = {["name"] = "hood",           			    ["label"] = "Hood",	 			    ["weight"] = 2500, 		["type"] = "item", 		["image"] = "hood.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle hood"},
    ["trunk"] 		 	 	    	 = {["name"] = "trunk",           			    ["label"] = "Trunk",	 			["weight"] = 2500, 		["type"] = "item", 		["image"] = "trunk.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle trunk"},
    ["doors"] 		 	 	    	 = {["name"] = "doors",           			    ["label"] = "Doors",	 			["weight"] = 5000, 		["type"] = "item", 		["image"] = "doors.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Some vehicle doors"},
    ["engine"] 		 	 	    	 = {["name"] = "engine",           			    ["label"] = "Engine",	 			["weight"] = 5000, 		["type"] = "item", 		["image"] = "engine.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle engine"},
    ["waterpump"] 		 	 	     = {["name"] = "waterpump",           			["label"] = "Water Pump",	 	    ["weight"] = 500, 		["type"] = "item", 		["image"] = "waterpump.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle water pump"},
    ["oilpump"] 		 	 	     = {["name"] = "oilpump",           			["label"] = "Oil Pump",	 	        ["weight"] = 500, 		["type"] = "item", 		["image"] = "oilpump.png", 		    ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle oil pump"},
    ["speakers"] 		 	 	     = {["name"] = "speakers",           			["label"] = "Speakers",	 	        ["weight"] = 1500, 		["type"] = "item", 		["image"] = "speakers.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Some vehicle speakers"},
    ["car_radio"] 		 	 	     = {["name"] = "car_radio",           			["label"] = "Car Radio",	 	    ["weight"] = 500, 		["type"] = "item", 		["image"] = "car_radio.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle radio"},
    ["rims"] 		 	 	         = {["name"] = "rims",           		    	["label"] = "Rims",	 	            ["weight"] = 1500, 		["type"] = "item", 		["image"] = "rims.png", 		    ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "Some vehicle rims"},
    ["subwoofer"] 		 	 	     = {["name"] = "subwoofer",           		    ["label"] = "Subwoofer",	 	    ["weight"] = 1000, 		["type"] = "item", 		["image"] = "subwoofer.png", 	    ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle subwoofer"},
    ["steeringwheel"] 		 	 	 = {["name"] = "steeringwheel",           	    ["label"] = "Steering Wheel",	 	["weight"] = 1000, 		["type"] = "item", 		["image"] = "steeringwheel.png",    ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = true,   ["combinable"] = nil,   ["description"] = "A vehicle steering wheel"},
]]
